### ISSUE TITLE
一直部署失败，请问如何解决？

### ISSUE THREAD

**Issue by WilsonWu315** [OpenLMLab/MOSS#125]
在A100一张/3090两张的机器部署，得到都是一样的错误，请问如何解决？

欢迎使用 MOSS 人工智能助手！输入内容即可进行对话。输入 clear 以清空对话历史，输入 stop 以终止对话。
<|Human|>: 你好
Traceback (most recent call last):
  File "moss_cli_demo.py", line 89, in <module>
    main()
  File "moss_cli_demo.py", line 72, in main
    outputs = model.generate(
  File "/root/miniconda3/envs/moss/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/moss/lib/python3.8/site-packages/transformers/generation/utils.py", line 1358, in generate
    if pad_token_id is not None and torch.sum(inputs_tensor[:, -1] == pad_token_id) > 0:
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by xiami2019** [comment]
看起来是torch和CUDA版本没对上
