### ISSUE TITLE
部署后报错问题。

### ISSUE THREAD

**Issue by mlpxt** [OpenLMLab/MOSS#126]
我的windows内存为48G，存储为500G，GPU最大为24G，这个配置是否可以部署出来MOSS，而且在我想要使用gui的界面时候一直提示以下信息，

-------------------------------------
(moss) PS E:\MOSS> python moss_gui_demo.py
Fetching 17 files: 100%|████████████████████████████████████████████████████████████████████| 17/17 [00:00<?, ?it/s]
Waiting for all devices to be ready, it may take a few minutes...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\gradio\routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\gradio\blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "moss_gui_demo.py", line 121, in predict
    inputs.input_ids.cuda(),
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\torch\cuda\__init__.py", line 208, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

-------------------------------------
初步推断是CUDA有问题，
请问该如何解决，
期待您的回复。

**Comment by piglaker** [comment]
您好，从报错信息来看可能是没有安装正确的torch版本，

**Comment by mlpxt** [comment]
![图片](https://user-images.githubusercontent.com/108312263/234042787-b0372b1f-b754-4ff5-a57c-73ab901bfd15.png)
您好，我使用的是这个版本的torch，请问这个可以吗，如果不可以，请提供一下可用的版本。

**Comment by piglaker** [comment]
请安装pytorch gpu 1.13.1 ：https://pytorch.org/
