### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by mlpxt** [OpenLMLab/MOSS#131]
在执行python .\moss_gui_demo.py后在web界面输入语句，没有出现回应，shell界面显示以下信息，

部署机器为windows10，内存大小为48G，GPU大小为24G，

----------------------------------------------------------
(moss) PS E:\MOSS> python .\moss_gui_demo.py
Fetching 17 files: 100%|█████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 17164.94it/s]
Waiting for all devices to be ready, it may take a few minutes...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\gradio\routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\gradio\blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File ".\moss_gui_demo.py", line 121, in predict
    inputs.input_ids.cuda(),
  File "C:\Users\admin\miniconda3\envs\moss\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

--------------------------------------------------------

而且在执行后查看任务管理器发现，内存占用率为30G左右，GPU占用大小为18%，这个属于正常现象吗？

请问，该如何解决这个问题

期待您的回复、

**Comment by cnsky2016** [comment]
Torch not compiled with CUDA enabled
应该是Torch版本的问题，你这个可能是CPU版本的，需要安装GPU版本的
