### ISSUE TITLE
按照步骤安装完成运行moss_cli_demo.py报错

### ISSUE THREAD

**Issue by xiaohe-person** [OpenLMLab/MOSS#161]
Fetching 17 files: 100%|████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 17033.72it/s]
Waiting for all devices to be ready, it may take a few minutes...
Traceback (most recent call last):
  File "moss_cli_demo.py", line 31, in <module>
    model = load_checkpoint_and_dispatch(
  File "D:\workspace\install\miniconda3\lib\site-packages\accelerate\big_modeling.py", line 479, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "D:\workspace\install\miniconda3\lib\site-packages\accelerate\utils\modeling.py", line 872, in load_checkpoint_in_model
    raise ValueError(
ValueError: At least one of the model submodule will be offloaded to disk, please pass along an `offload_folder`.

**Comment by xiami2019** [comment]
显存不够时需要在load_checkpoint_and_dispatch函数中指定一下offload_folder参数。

**Comment by zshmbbs** [comment]
手动建立一个目录，然后在load_checkpoint_and_dispatch里添加offload_folder参数，并且指向这个目录。注意目录的可写权限。
