### ISSUE TITLE
torch1.10.1，cuda11.3，推理时报错RuntimeError: CUDA error：no kernel image...是因为显存不够吗，3080显卡

### ISSUE THREAD

**Issue by Ben2522662** [OpenLMLab/MOSS#183]

**Comment by Ben2522662** [comment]
python moss_cli_demo.py
Fetching 17 files: 100%|██████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 83787.51it/s]
Waiting for all devices to be ready, it may take a few minutes...
欢迎使用 MOSS 人工智能助手！输入内容即可进行对话。输入 clear 以清空对话历史，输入 stop 以终止对话。
<|Human|>: hello
Traceback (most recent call last):
  File "moss_cli_demo.py", line 89, in <module>
    main()
  File "moss_cli_demo.py", line 72, in main
    outputs = model.generate(
  File "/root/miniconda3/envs/moss2/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/moss2/lib/python3.8/site-packages/transformers/generation/utils.py", line 1358, in generate
    if pad_token_id is not None and torch.sum(inputs_tensor[:, -1] == pad_token_id) > 0:
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by Ben2522662** [comment]
补充下环境信息：
(moss2) [root@asr MOSS]# conda list torch
# packages in environment at /root/miniconda3/envs/moss2:
#
# Name                    Version                   Build  Channel
torch                     1.10.1                   pypi_0    pypi
torchaudio                0.9.0                    pypi_0    pypi
torchvision               0.10.0+cu111             pypi_0    pypi
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~·~~~~~~~~~~~~~

(moss2) [root@asr MOSS]# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(moss2) [root@asr MOSS]# nvidia-smi
Thu Apr 27 09:34:23 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:18:00.0 Off |                  N/A |
| 30%   31C    P8    17W / 320W |   9970MiB / 10240MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     40411      C   python                           9968MiB |
+-----------------------------------------------------------------------------+

**Comment by yhyu13** [comment]
requirement.txt中要求pytorch==1.13.1，这个py版本好像已经没有cuda11.3了，应该用pytorch-1.13.1cu117。
同时，没有应用量化的话，fp16需要32G显存，3080肯定不够的
运行量化版本需要编译gptq，需要安装cuda tool kit进行编译，和pytorch一个cuda版本
