### ISSUE TITLE
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1-2: surrogates not allowed

### ISSUE THREAD

**Issue by dydwgmcnl4241** [OpenLMLab/MOSS#23]
欢迎使用 MOSS 人工智能助手！输入内容即可进行对话。输入 clear 以清空对话历史，输入 stop 以终止对话。
<|Human|>: 你好
Traceback (most recent call last):
  File "moss_cli_demo.py", line 85, in <module>
    main()
  File "moss_cli_demo.py", line 67, in main
    inputs = tokenizer(prompt, return_tensors="pt")
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2530, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2636, in _call_one
    return self.encode_plus(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2709, in encode_plus
    return self._encode_plus(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 649, in _encode_plus
    first_ids = get_input_ids(text)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 616, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 547, in tokenize
    tokenized_text.extend(self._tokenize(token))
  File "/root/MOSS/models/tokenization_moss.py", line 244, in _tokenize
    self.byte_encoder[b] for b in token.encode("utf-8")
    UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1-2: surrogates not allowed

    请问这个问题怎么解决呢？谢谢~

**Comment by dydwgmcnl4241** [comment]
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/122611406/233671154-846d93a1-2a70-48c2-9f16-4bb30ede591d.png">
间歇性发作。。

**Comment by xiami2019** [comment]
@00INDEX

**Comment by 00INDEX** [comment]
您好，您遇到的问题是由于您的输入包含了非 `UTF-8` 编码的字符，您可以：

1. 检查您的输入，并删除非 `UTF-8` 编码的字符；
2. 检查您的终端设置，并将默认编码设置为 `UTF-8`。

**Comment by Argon4W** [comment]
在Windows 11的WSL2 Ubuntu22.04, 终端为Windows Terminal的环境下, 删除中文字符会导致utf8的解码错误, 推测可能是没有完全删掉字符所致, 不清楚在其他测试环境下的表现如何
