### ISSUE TITLE
Finetune提示out of memory

### ISSUE THREAD

**Issue by Tian14267** [OpenLMLab/MOSS#297]
大神们好。我在4张A100上进行finetune，batch=1。但是还是会提示 `out of memory`。请问是啥情况啊

**Comment by Tian14267** [comment]
调整成max_len = 1024，也同样会`out of memory`
![image](https://github.com/OpenLMLab/MOSS/assets/27938135/07290b7a-1a8f-4afb-8d2d-f8e7214905fc)

**Comment by yangzhipeng1108** [comment]
需要8张A100，可以参考这个，int8也可以精调了
https://github.com/yangzhipeng1108/moss-finetune-and-moss-finetune-int8

**Comment by Tian14267** [comment]
@yangzhipeng1108 我想问下，每张A100的卡，能加载完整的模型吗？如果可以的话，为啥4张不行呀。不太明白~
另外，int8也可以finetune吗？我试试

**Comment by yangzhipeng1108** [comment]
deepspeed_config:  zero_stage: 3  moss的配置是deepspeed stage3 模型是分开加载到跟个模型，我使用1batch_size,8卡的瞬时基本每张卡都到70G显存以上了，官网没有开源，我改好，目前int8可以finetune

**Comment by Tian14267** [comment]
@yangzhipeng1108 明白你的意思。真正训练的话，还是得模型分散加载到各个卡里是吧。这个MOSS也没开源。不知道大神你有没有能实现这样的。目前只能用int8。

**Comment by yangzhipeng1108** [comment]
只要8张A100或者A800就能官方的只是finetune，官方finetune后16B的半精度推理速度太慢才考虑8int，我的项目里8int可以finetune

**Comment by yangzhipeng1108** [comment]
只要8张A100或者A800就能官方的实现finetune，官方finetune后16B的半精度推理速度太慢才考虑8int，我的项目里8int可以finetune

**Comment by Tian14267** [comment]
@yangzhipeng1108 嗯嗯。对了，我在训练int8的时候，遇到一些问题：**run_int8_acc.sh**

```
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 39133) of binary: /opt/conda/envs/moss/bin/python3.8
Traceback (most recent call last):
  File "/opt/conda/envs/moss/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/accelerate/commands/launch.py", line 909, in launch_command
    multi_gpu_launcher(args)
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/accelerate/commands/launch.py", line 604, in multi_gpu_launcher
    distrib_run.run(args)
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune_moss_int8_acc.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-05-19_06:14:22
  host      : df-instance-2.asia-southeast1-c.c.dingfuzhineng-aigc.internal
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 39134)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-05-19_06:14:22
  host      : df-instance-2.asia-southeast1-c.c.dingfuzhineng-aigc.internal
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 39135)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-05-19_06:14:22
  host      : df-instance-2.asia-southeast1-c.c.dingfuzhineng-aigc.internal
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 39136)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-19_06:14:22
  host      : df-instance-2.asia-southeast1-c.c.dingfuzhineng-aigc.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 39133)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

请问你知道是啥问题嘛

**Comment by Tian14267** [comment]
@yangzhipeng1108 哈喽你好，我这边一直提示下面这个错误：
```

	size mismatch for transformer.h.31.attn.qkv_proj.qweight: copying a param with shape torch.Size([1536, 18432]) from checkpoint, the shape in current model is torch.Size([768, 18432]).
	size mismatch for transformer.h.31.attn.qkv_proj.qzeros: copying a param with shape torch.Size([48, 4608]) from checkpoint, the shape in current model is torch.Size([48, 2304]).
	size mismatch for transformer.h.31.mlp.fc_in.qweight: copying a param with shape torch.Size([1536, 24576]) from checkpoint, the shape in current model is torch.Size([768, 24576]).
	size mismatch for transformer.h.31.mlp.fc_in.qzeros: copying a param with shape torch.Size([48, 6144]) from checkpoint, the shape in current model is torch.Size([48, 3072]).
	size mismatch for transformer.h.31.mlp.fc_out.qweight: copying a param with shape torch.Size([6144, 6144]) from checkpoint, the shape in current model is torch.Size([3072, 6144]).
	size mismatch for transformer.h.31.mlp.fc_out.qzeros: copying a param with shape torch.Size([192, 1536]) from checkpoint, the shape in current model is torch.Size([192, 768]).
	size mismatch for transformer.h.32.attn.out_proj.qweight: copying a param with shape torch.Size([1536, 6144]) from checkpoint, the shape in current model is torch.Size([768, 6144]).
	size mismatch for transformer.h.32.attn.out_proj.qzeros: copying a param with shape torch.Size([48, 1536]) from checkpoint, the shape in current model is torch.Size([48, 768]).
	size mismatch for transformer.h.32.attn.qkv_proj.qweight: copying a param with shape torch.Size([1536, 18432]) from checkpoint, the shape in current model is torch.Size([768, 18432]).
	size mismatch for transformer.h.32.attn.qkv_proj.qzeros: copying a param with shape torch.Size([48, 4608]) from checkpoint, the shape in current model is torch.Size([48, 2304]).
	size mismatch for transformer.h.32.mlp.fc_in.qweight: copying a param with shape torch.Size([1536, 24576]) from checkpoint, the shape in current model is torch.Size([768, 24576]).
	size mismatch for transformer.h.32.mlp.fc_in.qzeros: copying a param with shape torch.Size([48, 6144]) from checkpoint, the shape in current model is torch.Size([48, 3072]).
	size mismatch for transformer.h.32.mlp.fc_out.qweight: copying a param with shape torch.Size([6144, 6144]) from checkpoint, the shape in current model is torch.Size([3072, 6144]).
	size mismatch for transformer.h.32.mlp.fc_out.qzeros: copying a param with shape torch.Size([192, 1536]) from checkpoint, the shape in current model is torch.Size([192, 768]).
	size mismatch for transformer.h.33.attn.out_proj.qweight: copying a param with shape torch.Size([1536, 6144]) from checkpoint, the shape in current model is torch.Size([768, 6144]).
	size mismatch for transformer.h.33.attn.out_proj.qzeros: copying a param with shape torch.Size([48, 1536]) from checkpoint, the shape in current model is torch.Size([48, 768]).
	size mismatch for transformer.h.33.attn.qkv_proj.qweight: copying a param with shape torch.Size([1536, 18432]) from checkpoint, the shape in current model is torch.Size([768, 18432]).
	size mismatch for transformer.h.33.attn.qkv_proj.qzeros: copying a param with shape torch.Size([48, 4608]) from checkpoint, the shape in current model is torch.Size([48, 2304]).
	size mismatch for transformer.h.33.mlp.fc_in.qweight: copying a param with shape torch.Size([1536, 24576]) from checkpoint, the shape in current model is torch.Size([768, 24576]).
	size mismatch for transformer.h.33.mlp.fc_in.qzeros: copying a param with shape torch.Size([48, 6144]) from checkpoint, the shape in current model is torch.Size([48, 3072]).
	size mismatch for transformer.h.33.mlp.fc_out.qweight: copying a param with shape torch.Size([6144, 6144]) from checkpoint, the shape in current model is torch.Size([3072, 6144]).
	size mismatch for transformer.h.33.mlp.fc_out.qzeros: copying a param with shape torch.Size([192, 1536]) from checkpoint, the shape in current model is torch.Size([192, 768]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 762) of binary: /opt/conda/envs/moss/bin/python3.8
Traceback (most recent call last):
  File "/opt/conda/envs/moss/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/accelerate/commands/launch.py", line 909, in launch_command
    multi_gpu_launcher(args)
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/accelerate/commands/launch.py", line 604, in multi_gpu_launcher
    distrib_run.run(args)
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/moss/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

是不是尺寸不对啊，这个是啥情况

**Comment by lhtpluto** [comment]
> deepspeed_config: zero_stage: 3 moss的配置是deepspeed stage3 模型是分开加载到跟个模型，我使用1batch_size,8卡的瞬时基本每张卡都到70G显存以上了，官网没有开源，我改好，目前int8可以finetune

大神，是指int8 的finetune 需要80GB*8的显存吗？  不知道48GB*8的显存能否finetune？

**Comment by yangzhipeng1108** [comment]
精调moss需要，int8不需要

**Comment by yangzhipeng1108** [comment]
> > deepspeed_config: zero_stage: 3 moss的配置是deepspeed stage3 模型是分开加载到跟个模型，我使用1batch_size,8卡的瞬时基本每张卡都到70G显存以上了，官网没有开源，我改好，目前int8可以finetune
> 
> 大神，是指int8 的finetune 需要80GB_8的显存吗？ 不知道48GB_8的显存能否finetune？
精调moss需要，int8不需要

**Comment by yangzhipeng1108** [comment]
> > deepspeed_config: zero_stage: 3 moss的配置是deepspeed stage3 模型是分开加载到跟个模型，我使用1batch_size,8卡的瞬时基本每张卡都到70G显存以上了，官网没有开源，我改好，目前int8可以finetune
> 
> 大神，是指int8 的finetune 需要80GB_8的显存吗？ 不知道48GB_8的显存能否finetune？

精调moss需要，int8不需要
