### ISSUE TITLE
ValueError: Unable to compare versions for numpy>=1.17: need=1.17 found=None. This is unusual. Consider reinstalling numpy.

### ISSUE THREAD

**Issue by daipeihust** [OpenLMLab/MOSS#31]
```
> python3 moss_cli_demo.py
Traceback (most recent call last):
  File "/Users/daipei/Code/MOSS/moss_cli_demo.py", line 8, in <module>
    from transformers.generation.utils import logger
  File "/usr/local/lib/python3.11/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.11/site-packages/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "/usr/local/lib/python3.11/site-packages/transformers/utils/versions.py", line 123, in require_version_core
    return require_version(requirement, hint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/utils/versions.py", line 117, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/usr/local/lib/python3.11/site-packages/transformers/utils/versions.py", line 45, in _compare_versions
    raise ValueError(
ValueError: Unable to compare versions for numpy>=1.17: need=1.17 found=None. This is unusual. Consider reinstalling numpy.
```

**Comment by piglaker** [comment]
重装下numpy试试，确保你在新的虚拟环境下从头构建
