### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'deepspeed_config'

### ISSUE THREAD

**Issue by HDRBgg** [OpenLMLab/MOSS#80]
Traceback (most recent call last):
  File "finetune_moss.py", line 303, in <module>
    train(args)
  File "finetune_moss.py", line 175, in train
    accelerator.state.deepspeed_plugin.deepspeed_config['train_micro_batch_size_per_gpu'] = args.train_bsz_per_gpu
AttributeError: 'NoneType' object has no attribute 'deepspeed_config'

**Comment by flomok** [comment]
Hi,I have the same mistake,have you solve it？

**Comment by HDRBgg** [comment]
> 

分布式训练的问题，还没解决

**Comment by lby129** [comment]
你好，请问解决了吗？我也遇到同样的问题。

**Comment by flomok** [comment]
不好意思，我也没有解决呢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenLMLab/MOSS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月5日(星期五) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenLMLab/MOSS] AttributeError: 'NoneType' object has no attribute 'deepspeed_config' (Issue #80)





 
你好，请问解决了吗？我也遇到同样的问题。

**Comment by hjing100** [comment]
同样的问题，请问解决了吗
运行报错：
python finetune_moss.py --model_name_or_path /web/pretrained_model/moss-moon-003-sft --data_dir ./SFT_data --output_dir ./ckpts/moss-moon-003-sft --log_dir ./train_logs/moss-moon-003-sft --n_epochs 2 --train_bsz_per_gpu 4 --eval_bsz_per_gpu 4 --learning_rate 0.000015 --eval_step 200 --save_step 2000

**Comment by KickyGong** [comment]
我也遇到了同样的问题，除了存储路径之外没动别的参数。会不会是某些包的版本的问题？

**Comment by Taurus0423** [comment]
我也遇到同样的问题，各位解决了吗？
