### ISSUE TITLE
INT4量化版本运行提示name 'autotune' is not defined

### ISSUE THREAD

**Issue by cnsky2016** [OpenLMLab/MOSS#85]
已经安装triton、autotune

triton not installed. Run `pip install triton` to load quantized version of MOSS.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/moss/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 458, in from_pretrained
    return model_class.from_pretrained(
  File "/root/anaconda3/envs/moss/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2276, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/local/modeling_moss.py", line 608, in __init__
    self.quantize(config.wbits, config.groupsize)
  File "/root/.cache/huggingface/modules/transformers_modules/local/modeling_moss.py", line 732, in quantize
    from .quantization import quantize_with_gptq
  File "/root/.cache/huggingface/modules/transformers_modules/local/quantization.py", line 27, in <module>
    @autotune(
NameError: name 'autotune' is not defined

**Comment by JxiaoC** [comment]
+1

**Comment by DefengXie** [comment]
把quantization.py 里的
try: 
import triton import triton.language as tl 
from .custom_autotune import * 
except:
这段
改成
try: 
import triton import triton.language as tl 
from custom_autotune import * 
except:

删除掉transformers cache
重启就可以

**Comment by yfq512** [comment]
> transformers cache

transformers cache 在哪？怎么删除？
