### ISSUE TITLE
使用moss-moon-003-sft-plugin-int4后报错

### ISSUE THREAD

**Issue by Chun-QiuCC** [OpenLMLab/MOSS#90]
按照readme中的内容安装的对应环境，并修改了moss_cli_demo.py中的第20行为
`model_path = "fnlp/moss-moon-003-sft-plugin-int4"`
运行python moss_cli_demo.py后输出内容如下：
```
(moss) PS F:\MOSS\moss> python moss_cli_demo.py
Waiting for all devices to be ready, it may take a few minutes...
triton not installed. Run `pip install triton` to load quantized version of MOSS.
Traceback (most recent call last):
  File "moss_cli_demo.py", line 29, in <module>
    raw_model = MossForCausalLM._from_config(config, torch_dtype=torch.bfloat16)
  File "E:\miniconda\envs\moss\lib\site-packages\transformers\modeling_utils.py", line 1024, in _from_config
    model = cls(config, **kwargs)
  File "F:\MOSS\moss\models\modeling_moss.py", line 612, in __init__
    self.quantize(config.wbits, config.groupsize)
  File "F:\MOSS\moss\models\modeling_moss.py", line 736, in quantize
    from .quantization import quantize_with_gptq
  File "F:\MOSS\moss\models\quantization.py", line 27, in <module>
    @autotune(
NameError: name 'autotune' is not defined
```

**Comment by littlestone0806** [comment]
这个是因为官方的int4模型用了triton库，但是这个库目前只支持linux，windows装不上

**Comment by Chun-QiuCC** [comment]
> 这个是因为官方的int4模型用了triton库，但是这个库目前只支持linux，windows装不上

请问如果我想在Windows环境下运行MOSS的话只能运行8bit量化版本吗？

**Comment by littlestone0806** [comment]
> > 这个是因为官方的int4模型用了triton库，但是这个库目前只支持linux，windows装不上
> 
> 请问如果我想在Windows环境下运行MOSS的话只能运行8bit量化版本吗？

int8和int4都用了triton，都用不了。只能用全精度的，但是全精度直接上30G显存，大部分显卡都跑不了，很无语

**Comment by Chun-QiuCC** [comment]
> > > 这个是因为官方的int4模型用了triton库，但是这个库目前只支持linux，windows装不上
> > 
> > 
> > 请问如果我想在Windows环境下运行MOSS的话只能运行8bit量化版本吗？
> 
> int8和int4都用了triton，都用不了。只能用全精度的，但是全精度直接上30G显存，大部分显卡都跑不了，很无语

好吧，感谢

**Comment by piglaker** [comment]
Duplicate of #68

**Comment by piglaker** [comment]
#65 一个可能的解决方案
